### ISSUE TITLE
epd_msgs's srv and client are not provided

### ISSUE THREAD

**Issue by Promethees** [ros-industrial/easy_manipulation_deployment#10]
In order to have **get grasp_planning** being a subscriber of topic **/processor/epd_localize_output**, the **/grasp_planner/include/grasp_planner/grasp_scene.cpp** should be proceeded. In its header file, **grasp_scene.hpp**, whenever global variable **EPD_ENABLED** is set to 1, which indicate the availability of **epd_msgs**, the **epd_msgs/srv/perception.hpp** is needed for importing services and clients:
![Screenshot from 2021-12-16 16-18-45](https://user-images.githubusercontent.com/51523975/146335679-89375012-ccee-4951-8914-5431711ca007.png)
![Screenshot from 2021-12-16 16-19-33](https://user-images.githubusercontent.com/51523975/146335695-b66ceb67-b76f-4c58-9662-170de6a90bc3.png)
Unfortunately, the **/srv** folder under **epd_msgs** seems to be missed out from **easy_perception_deployment** source code
![Screenshot from 2021-12-16 16-19-59](https://user-images.githubusercontent.com/51523975/146335871-a8fd6c0a-538d-4272-8099-d5310e030678.png)
This issue leads to the unavailability of integration between epd's localization and emd's grasp planner.
Is there any way can I resolve it?

**Comment by cardboardcode** [comment]
Hi @Promethees, thank you for identifying this issue. Working on it. 

Will update once the /srv folder has been properly updated over at EPD.

**Comment by cardboardcode** [comment]
Hi @Promethees,

A hot fix has been introduced over at EPD under [a forked repository](https://github.com/cardboardcode/easy_perception_deployment/commit/bf3ba2247fdddd1c6197762a5be453efd7031e02).

Please use the following forked repository while the Continuous Integration (CI) issues are being resolved before merging into the official ros-industrial repository:
```bash
git clone https://github.com/cardboardcode/easy_perception_deployment.git
```

Do let us know if this resolves this issue for you. Will update again once the fix has been merged officially.

**Comment by Promethees** [comment]
Hi, I really appreciate for the prompt response and the fix! However, I'm still confused for the missing of a file called epd_msgs/srv/Perception.srv. Is this still the one hasn't been uploaded yet?
![Screenshot from 2021-12-19 23-27-56](https://user-images.githubusercontent.com/51523975/146680821-0cf63e00-b551-43cd-8b43-e5e6646e3ff6.png)
![Screenshot from 2021-12-19 23-31-28](https://user-images.githubusercontent.com/51523975/146680845-7becf9f1-c36d-42c7-b821-2ba4a446ffb9.png)

**Comment by cardboardcode** [comment]
**It has been added.** Just not specifically in the latest commit. 

Please refer to [this commit](https://github.com/cardboardcode/easy_perception_deployment/commit/6e8eeb2f8dc686c7c0a944436d9873c2f4226e5d).

However, **please still use the latest commit as highlighted above** since simply including the `.srv` file is not enough. There are features in place in EPD that makes use of it.

**Comment by Promethees** [comment]
Ah, it appears that my ros is a little bit behind after an instant merge(i.e: it should take a while for ros's cmake to recognize the existence of the newly added Perception.srv to do the build). Anyways, this issue is solved, thanks a lot!

**Comment by cardboardcode** [comment]
> Hi @Promethees,
> 
> A hot fix has been introduced over at EPD under [a forked repository](https://github.com/cardboardcode/easy_perception_deployment/commit/bf3ba2247fdddd1c6197762a5be453efd7031e02).
> 
> Please use the following forked repository while the Continuous Integration (CI) issues are being resolved before merging into the official ros-industrial repository:
> 
> ```shell
> git clone https://github.com/cardboardcode/easy_perception_deployment.git
> ```
> 
> Do let us know if this resolves this issue for you. Will update again once the fix has been merged officially.

The fix has been merged officially into ros-industrial's `easy_perception_deployment` [[link]](https://github.com/ros-industrial/easy_perception_deployment).
