### ISSUE TITLE
Error: terminate called after throwing an instance of 'eprosima::fastcdr::exception::NotEnoughMemoryException' what(): Not enough memory in the buffer stream

### ISSUE THREAD

**Issue by Dcrypt** [ros-industrial/easy_manipulation_deployment#3]
Hi, I want to use EMD grasp planner with EPD object localisation. After I source to the EMD workspace, the grasp planner raised this error. While sourcing to EMD workspace, I also can not echo out from the topic /processor/epd_localize_output. However, I can echo from the topic when sourcing from EPD's epd_msgs workspace only. After some investigation and reinstalling fastcdr, I found out that the actual problem is caused by the different message used in EPDObjectLocalization.msg. Currently, the EPD does not include all of the EMD field types in that message type.

I have changed the EPD's EPDObjectLocalization.msg to follow the EMD's. I can now echo and run the grasp planner while sourcing from EMD. However, the grasp planner feedback that there is no object detected despite placing the identified object in camera field of view. 

Fieldtypes missing in EPD's EPDObjectLocalization.msg
```
uint32 num_objects
sensor_msgs/CameraInfo camera_info
sensor_msgs/RegionOfInterest[] roi_array
```

**Comment by tanjpg** [comment]
Hi, Thanks for bringing this to our attention. Could you try running EPD again using the newly created **emd-alpha-compatible** branch? The ros2 messages should be consistent now.

The easy manipulation deployment package is currently undergoing some fundamental changes that will support point cloud grasp planning and multiple end effector support, which will be compatible with the latest EPD version, but we are currently in the process of preparing that version for release in the coming month. For now this EPD branch should support the current public version of EMD.
